version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lorrigo
      - NODE_ENV=production
      - API_URL=http://api:3000
    depends_on:
      - api
      - db
    networks:
      - lorrigo-network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lorrigo
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - lorrigo-network

  workers:
    build:
      context: .
      dockerfile: apps/workers/Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lorrigo
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - lorrigo-network

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lorrigo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lorrigo-network

networks:
  lorrigo-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local 