version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: lorrigo-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: lorrigo
      POSTGRES_PASSWORD: lorrigo
      POSTGRES_DB: lorrigo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lorrigo-network

  # Redis for caching, rate limiting, and job queues
  redis:
    image: redis:alpine
    container_name: lorrigo-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - lorrigo-network

  # API Server
  api:
    image: ${DOCKER_HUB_USERNAME:-aloksharma10969}/lorrigo-api:latest
    container_name: lorrigo-api
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=postgresql://lorrigo:lorrigo@postgres:5432/lorrigo?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=4000
      - NODE_ENV=development
      - API_VERSION=v2
      - API_PREFIX=/api
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/api/node_modules
    networks:
      - lorrigo-network

  # Web Frontend
  web:
    image: ${DOCKER_HUB_USERNAME:-aloksharma10969}/lorrigo-web:latest
    container_name: lorrigo-web
    restart: always
    depends_on:
      - api
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/web/node_modules
    networks:
      - lorrigo-network

  # Notification Service
  notifications:
    image: ${DOCKER_HUB_USERNAME:-aloksharma10969}/lorrigo-notifications:latest
    container_name: lorrigo-notifications
    restart: always
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://lorrigo:lorrigo@postgres:5432/lorrigo?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
    volumes:
      - ./apps/notifications:/app/apps/notifications
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/notifications/node_modules
    networks:
      - lorrigo-network

  # Worker Service for background jobs
  workers:
    image: ${DOCKER_HUB_USERNAME:-aloksharma10969}/lorrigo-workers:latest
    container_name: lorrigo-workers
    restart: always
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://lorrigo:lorrigo@postgres:5432/lorrigo?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
      - QUEUE_CONCURRENCY=3
    volumes:
      - ./apps/workers:/app/apps/workers
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/workers/node_modules
    networks:
      - lorrigo-network

networks:
  lorrigo-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: 